### ISSUE TITLE
Carbon Laravel CheetSheet would be awesome

### ISSUE THREAD

**Issue by vignesh0025-zz** [Aufree/laravel5-cheatsheet#5]
It would be awesome if a sheet exists for Carbon Also :+1:

**Comment by summerblue** [comment]
great idea.

**Comment by summerblue** [comment]
Carbon is too big to fit in, too many APIs, and if we support Carbon, what about Faker and bunch other third party libraries.

**Comment by vignesh0025-zz** [comment]
Exactly... Carbon is too big and I can't find what i want. There were times when i wrote a 20 lines code to do a job and then find an API already is present to do it. That's why I require a cheat sheet. Considering Faker... Its huge !
